DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  upvotes INTEGER,
  FOREIGN KEY (author_id) REFERENCES user (id)
)